export default {
  // commands (utils.ts)
  'any-block-rebuild-view': 'Refresh/rebuild current view',
  'any-block-rebuild-view-btn': 'Rebuild View',

  'any-block-to-codeblock': 'Convert anyblock section into codeblock format',
  'any-block-to-codeblock-success': 'Convert success! Generated to ',
  'any-block-to-codeblock-fail': 'Convert failed, please check the console for details',

  'any-block-delete-ab-header': 'Delete AnyBlock header',
  'any-block-switch-disable': 'Toggle AnyBlock enable/disable',

  // setting.ts
  'Mini docs': `Mini docs`,
  'see website for detail': `See 
    <a href="https://lincdocs.github.io/AnyBlock/README.show.html">website</a>
    /
    <a href="https://github.com/LincZero/obsidian-any-block">github</a>
    for more details | Author: <a href="https://github.com/LincZero">LincZero</a>`,
  'Mini docs menu': `How to visualize the creation of AnyBlock?`,
  'Mini docs menu2': `It is recommended to use
    <a href="https://github.com/any-menu/any-menu">AnyMenu</a>
    plugin (developed by the same author) to quickly enter AnyBlock templates using the menu panel or search box.`,

  'Selector manager': 'Selector',
  'Selector manager2': 'This section is for query only and cannot be edited',

  'AliasSystem manager': 'Alias system',
  'AliasSystem manager2': 'It can be viewed in the main page using the `[info_alias]` processor',
  'AliasSystem manager3': 'This section can also be modified by opening the `data.json` file in the plugin folder',
  'AliasSystem manager4': 'Add a new registration instruction',
  'AliasSystem manager5': 'Add a new registration instructionAdd a new registration instruction (old, will not be used)',

  'Convertor manager': 'Convertor',
  'Convertor manager2': 'It can be viewed in the main page using the `[info_converter]` processor',
  'Convertor manager3': 'This section is for query only and cannot be edited',

  'Custom alias': 'Custom alias',
  'Custom alias2': 'Alias matching rule',
  'Custom alias3': 'If `/` is used to enclose it, it indicates a regular expression.',
  'Custom alias4': 'Alias replacement',
  'Custom alias5': 'The parameter-based replacement function is currently not available. It will be enabled only when there is a need for multiple users.',

  'Custom processor': 'Custom processor - deprecated',
  'Custom processor2': 'Processor id',
  'Custom processor3': 'Without conflicting with other processors',
  'Custom processor4': 'Processor name',
  'Custom processor5': 'You can fill it in freely. It\'s for your own reference',
  'Custom processor6': 'Processor matching rule',
  'Custom processor7': 'Using `/` including it indicates a regular expression',
  'Custom processor8': 'Processor replacement',
  'Custom processor9': 'Using `/` including it indicates a regular expression',

  'Pro': 'Pro',
  'Pro2': 'Pro version enhanced settings',
  'Pro disable': 'Disable pro feat',
  'Pro disable2': '(The modification requires restarting the plugin) \
Disable the Pro version features. Once enabled, they will be equivalent to the non-Pro version functions. This is convenient for debugging bugs or checking whether the function is generated by this module.',
  'Pro editableblock render': 'EditableBlock default render',
  'Pro editableblock render2': 'EditableBlock default render mode',
  'Pro editableblock render21': '- Read mode: you need to press the middle key to enter the editing mode. Press the middle key / Esc / move the cursor outside to complete the editing.',
  'Pro editableblock render22': '- Teal time: allows for direct editing but requires more performance.',
  'Pro editableblock render23': '- Simple text area: Display as plain text, suitable for cases where the sub-block does not contain complex markdown.',
  'Pro editableblock render24': '- Only take over during editing (developing)',
  'Pro editableblock render3': 'Read mode',
  'Pro editableblock render4': 'Real mode',
  'Pro editableblock render5': 'Simple text area',
  'Pro alias override': 'Pro alias override',
  'Pro alias override2': '(The modification requires restarting the plugin) \
Replace the original processor behavior with the corresponding Pro processor behavior. If disabled, the editable version and the original version will use different processor names.',
  'Pro callout': 'Callout selector',
  'Pro callout2': 'Use the Callout selector and enable editable Callout',

  'License': 'License',
  'License2': 'This is a license for the Pro version. The display of expiration time needs to be updated by reopening the settings panel.\n\
By adopting a dual-licensing mechanism, a certain period of default free licenses (coexisting with the user licenses) will be provided with each update.',
  'License key': 'License key',
  'License Expiry': 'License Expiry. The display of expiration time needs to be updated by reopening the settings panel.',

  // General
  'Submit': 'Submit',
  'Edit': 'Edit',
  'Refresh': 'Refresh',
  'Delete': 'Delete',
  'Save': 'Save',
  'Cancel': 'Cancel',
  'Close': 'Close',
}
